# Generated by Django 6.0.1 on 2026-01-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FAY", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="role",
            field=models.CharField(
                choices=[("USER", "USER"), ("CREATOR", "CREATOR")], max_length=10
            ),
        ),
    ]
