# Generated by Django 6.0.1 on 2026-04-19 10:20

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FAY", "0003_event"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="event_type",
        ),
        migrations.AddField(
            model_name="profile",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="profile",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="event",
            name="event_types",
            field=models.ManyToManyField(
                blank=True, related_name="events_type", to="FAY.eventtype"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="event_types",
            field=models.ManyToManyField(
                blank=True, related_name="profile_events_type", to="FAY.eventtype"
            ),
        ),
    ]
