# Generated by Django 6.0.4 on 2026-04-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FAY", "0006_alter_event_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="profile/images/"),
        ),
        migrations.AddField(
            model_name="profile",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
